# -*- coding: utf-8 -*-
"""8_19121141_LazibShararShaiok.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UK2lYt-Uw8pVwlijXlJ3WyokdSWAhV3o
"""

#mounting drive and google
from google.colab import drive
drive.mount ('/content/drive')

#collecting data and neccessary libraries
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn import tree
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler
import seaborn as sns
from sklearn.svm import SVC
from sklearn.neural_network import MLPClassifier
from sklearn import svm
from sklearn.ensemble import RandomForestClassifier
from sklearn.decomposition import PCA
patients= pd.read_csv('/content/drive/MyDrive/melanoma/Melanoma TFRecords 256x256.csv')
patients.head(3)

#necesssary preprocessing
patients_subset=patients[patients['image_name'].notnull()]
patients_subset=patients_subset[patients_subset['patient_id'].notnull()]
patients_subset=patients_subset[patients['sex'].notnull()]
patients_subset=patients_subset[patients_subset['anatom_site_general_challenge'].notnull()]
patients_subset=patients_subset[patients_subset['diagnosis'].notnull()]
patients_subset=patients_subset[patients_subset['benign_malignant'].notnull()]
patients_subset=patients_subset[patients_subset['tfrecord'].notnull()]
patients_subset=patients_subset[patients_subset['width'].notnull()]
patients_subset=patients_subset[patients_subset['height'].notnull()]
patients_subset=patients_subset[patients_subset['patient_code'].notnull()]
patients_subset=patients_subset[patients_subset['age_approx'].notnull()]
patients_subset['sex']=patients_subset['sex'].map({'female':0,'male':1})
patients_subset['anatom_site_general_challenge']=patients_subset['anatom_site_general_challenge'].map({'head/neck':0,'upper extremity':1, 'lower extremity':2, 'palms/soles':3, 'oral/genital':4, 'torso':5})
patients_subset['diagnosis']=patients_subset['diagnosis'].map({'unknown':0,'nevus':1, 'melanoma':2, 'melanoma':3, 'seborrheic keratosis':4, 'lentigo NOS':5, 'lichenoid keratosis': 6, 'solar lentigo':7, 'cafe-au-lait macule':8, 'atypical melanocytic proliferation':9})
scaler=MinMaxScaler()
X=patients_subset[['sex','age_approx','anatom_site_general_challenge', 'diagnosis', 'tfrecord', 'width','height' ,'patient_code']]
Y=patients_subset[['target']]
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2 ,random_state = 1)
scaler.fit(X_train)
X_train=scaler.transform(X_train)
X_test= scaler.transform(X_test)

model= SVC(kernel="linear")
model.fit(x_train, y_train)
predictions = model.predict(x_test)
svc_acc=model.score(x_test, y_test)


model = MLPClassifier(hidden_layer_sizes=(7), activation="relu", max_iter=10000)
model.fit(X_train, y_train)
predictions = model.predict(X_test)

MLP_acc=accuracy_score(y_test, predictions)


model=RandomForestClassifier(n_estimators=100)

model.fit(X_train, y_train)


predictions = model.predict(X_test)

rndm_acc=accuracy_score(y_test, predictions)

pca = PCA(n_components=6)
x_train = pca.fit_transform(X_train)
x_test = pca.transform(X_test)
model = svm.SVC(kernel='linear')
model.fit(X_train, y_train) 
predictions = model.predict(X_test)
PCA_SVM=accuracy_score(y_test, predictions)
model = MLPClassifier(hidden_layer_sizes=(150,100,50), max_iter=300,activation = 'relu',solver='adam',random_state=1)
model.fit(X_train, y_train) 
predictions = model.predict(X_test)
PCA_MLP=accuracy_score(y_test, predictions)
model = RandomForestClassifier(n_estimators=100)
model.fit(X_train, y_train) 
predictions = model.predict(X_test)
PCA_RNDM=accuracy_score(y_test, predictions)

labels = ['SVM', 'MLP','RandomF']
norm = [svc_acc,MLP_acc,rndm_acc]
pca = [PCA_SVM,PCA_MLP,PCA_RNDM]
x = np.arange(len(labels))
fig, ax = plt.subplots()
rects1 = ax.bar(x -0.25,norm , width = 0.25, label='Pre PCA')
rects2 = ax.bar(x + 0, pca, width = 0.25, label='post PCA')
ax.set_xticks(x)
ax.set_xticklabels(labels)
ax.legend()
fig.tight_layout()
plt.show()